approve_by_comment: true
approve_regex: '^(Approved|LGTM|lgtm|:shipit:|:\+1:)'
reject_regex: '^(Rejected|:-1:)'
reset_on_push: false
reviewers:
  members:
  - jamox
  - juvester
  - ljleppan
  - matike
  - Mession
  - mikkomaa
  - nygrenh
  - Salmela
  - jclc
  name: default
  required: 1
  conditions:
    branches:
      - master  # only need to approve if merging to master
