language: java

script:
  - mvn -Dsurefire.rerunFailingTestsCount=3 cobertura:cobertura test
  - mvn checkstyle:check

after_success:
  - mvn coveralls:report

jdk:
  - oraclejdk8
  - oraclejdk7
  
cache:
  directories:
    - "$HOME/.m2"
