language: java
dist: trusty
script:
- mvn -Dsurefire.rerunFailingTestsCount=3 cobertura:cobertura test
- mvn checkstyle:check
after_success:
- mvn coveralls:report
- mvn clean package
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
      secure: "ilzHFmw1Wg0ktpY4JWRIk4ViZATEOvEB47exQMv86B+o9F4avyzBEnMbt/Id8hWtk+pvolvB/m55+Ul+z4DL8qhFo54RbKfLp7N/bxfot0n7ZFqvAhX3eKnZEQUBKDVX5o6nPaRNOTYOymgWQE9K4WjKyrcQ2oqAu/ebASZyMN96srE87f/2gcKMrKmrmwptKEuN4bA7dwZAMyoQrQcXZO1zpzEEZaW2w+9p7VJztYr0QfEmDs06JybdqZEwFkbJsq3riMUfGKUN+ugIl0mxafRMw8g5bavE3awyXUSYBmVHXhDDxt5n22wUJ6Jfr8nWjn6GhYzr/gn71K/oEgYb2siOo/N5SQe0ATuMpziR/s1dqMU67XDkQ15oQvY1gj1UxFMkXunQ2Ui+jdG31knTda469sQZdctiJ5XOA/p2iq30fLIs2BHD3KOtgXPSX6WXUYmSOjjECNUiqMbBuMdNrG6wM78cK04nm9wrc+vaa3rN/hmBZ1MfPd7u1VrE/IxlYZCyBoOxD6qwdIHWJAx7tAxo2GYDy0plaDOQfOzyY51TT0VPskhC5Pfu8Gl6J2XakLDZPbc0hwCs9DCgSEVtDeITJCHRbzShE6nhe0z1o7GcbEWMYW6j5QjQOVh3iPdAsUixBrpfM+YqLmE/1z3hkCI7MLg0h/5lujvDI6re/y8="
  file_glob: true
  file:
    - tmc
    - target/tmc-cli-*.jar
  on:
    repo: testmycode/tmc-cli
    tags: true
    jdk: oraclejdk8
